### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by dfarr**

### CODE REVIEW

**Comment by agraebe** [comment]
[CLA assistant check](https://cla-assistant.io/SAP/sap.github.com?pullRequest=6) <br/>All committers of the pull request should sign our Contributor License Agreement in order to get your pull request merged.

**Comment by sunilkumarc** [comment]
Why is this pull request not been merged yet? I think the project need a README.md file which describes the project.

**Comment by dfarr** [comment]
:+1:

**Comment by agraebe** [comment]
This PR was a sample to demonstrate functionality of https://cla-assistant.io/

**Pull request closed without merging**
